ALTER TABLE events DROP COLUMN IF EXISTS status;
ALTER TABLE events DROP COLUMN IF EXISTS updated_at;
ALTER TABLE users DROP COLUMN IF EXISTS role;

DROP TYPE IF EXISTS status_event;
DROP TYPE IF EXISTS user_role;